### ISSUE TITLE
Mobile Language Switcher

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/alphabet-keys#10]
Currently on Mobile (which is supported as of #9 ) we do not allow language switching like the desktop version. The menu exists but is just hidden on mobile size screens. We should allow switching languages on mobile size screens.

**Comment by ericadamski** [comment]
Sorry @motionsuggests I haven't merged my "mobile" version into master yet. You can take a look at #9 for the mobile version. Let me know if you have any questions from there!

**Comment by motionsuggests** [comment]
Got it. Thanks!

**Comment by higornevesmarques** [comment]
I did it :)

**Comment by ericadamski** [comment]
Merged in #9
