### ISSUE TITLE
Add a counting game

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/alphabet-keys#52]
It would be awesome to have more games that can teach things like counting! Something like, a number of the same emoji pops up and the user has to enter the number they see!

Really terrible text example:

🍎 🍎 🍎 
    
       3
       -

This will need a new menu screen to pick different games and a new input and validation flow.

**Comment by mankinchi** [comment]
@ericadamski I can work on this too :)

**Comment by mankinchi** [comment]
@ericadamski I'm thinking of adding FontAwesome into your project. Do you have anything against it?

**Comment by mankinchi** [comment]
Got the PR up and running ;)
