### ISSUE TITLE
Create a new Menu to allow people to select different games

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/alphabet-keys#56]
Currently when you visit https://alphabet-keys.now.sh/ it brings you right to a game. It would be good to have it bring you to a menu that has a list of games to play (see #52 and #53 about other potential games)

**Comment by mankinchi** [comment]
Can I start working on this?

**Comment by ericadamski** [comment]
@mankinchi of course! Save the PR for October if you are participating in https://hacktoberfest.digitalocean.com/ 🎃

**Comment by mankinchi** [comment]
@ericadamski I have already done and created a PR at https://github.com/ericadamski/alphabet-keys/pull/58. You are welcomed to preview and add any comments. I will save them for Hacktoberfest ;)

**Comment by mankinchi** [comment]
@ericadamski should this be closed?
