### ISSUE TITLE
No longer repeating words.

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/alphabet-keys#68]
See this deployment for what should happen when a letter is pressed https://alphabet-keys-hkq8a2oso.now.sh/

**Comment by Dev-Osmium** [comment]
What currently happens?

**Comment by ericadamski** [comment]
@Dev-Osmium it currently just repeats the letter pressed  see the current URL alphabet-keys.now.sh

**Comment by Dev-Osmium** [comment]
So when you press a different letter it just stays on the old letter? Apologies but I'm not quite understanding.

**Comment by ericadamski** [comment]
No worries! If you look at the link I posted in the original issue
description and you press a key for example 's' you will see an emoji that
starts with 's' then hear the text-to-speech API say the letter the say the
word that the emoji depicts.

Currently in the live version it only says the letter and fails to say the
word that the emoji represents.

Does that make sense? 😃

**Comment by ericadamski** [comment]
The culprit is this commit https://github.com/ericadamski/alphabet-keys/commit/90da108b5ff28af14de6064f10acc612ba3e9285
