### ISSUE TITLE
Add a link back to this repo from the site

### ISSUE THREAD

**Issue by ericadamski** [ericadamski/alphabet-keys#69]
Add a github icon that links back to this repo so people can explore the code!

**Comment by bpallares** [comment]
I will help you on this :)

**Comment by cantorsdustbunnies** [comment]
Would you like it in a particular position on the page (corners, centered)? I was going to work on this but it looks like bpallares beat me to the punch! So they might like to know :)

**Comment by ericadamski** [comment]
@cantorsdustbunnies @bpallares I will leave it up to the creator! I have no preference
